MyShop/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models
{
	public class Category
	{
		
		public int CategoryId { get; set; } //PK
        
		// Apply regular expression validation to CategoryName property
        [RegularExpression(@"^[a-zA-ZæøåÆØÅ. \-]{2,20}$", ErrorMessage = "Category name must consist of letters and be between 2 and 20 characters.")]
        public string CategoryName { get; set; } = string.Empty;

		// public string? Description { get; set; } //Add this if we decide we want a description for each category. 

		public virtual List<Room>? Rooms { get; set; } //One Category has 0 or more rooms. ? Means it can have 0.
    }
}

MyShop/Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models

{
    public class Comment
    {
        public int CommentId { get; set; } //PK
        public int PostId { get; set; } //FK

        public string? UserName { get; set; } //FK
        [Required]
        [MaxLength(10000)] // Eksempel: maximum length to 10000 character
        public string CommentDescription { get; set; }
        public DateTime CommentTime { get; set; }//Time of creation

        //Navigaiton property:
        public virtual Post? Post { get; set; } //Virtual enables lazy loading.
    }
}

MyShop/Models/Post.cs
using System.ComponentModel.DataAnnotations;



namespace Forum.Models

	{
	public class Post
	{
		public int PostId { get; set; } //PK
		public int TopicId { get; set; } //FK
		public string? UserName { get; set; } //FK

        // Apply regular expression validation to PostTitle property
        [Required]
        public string PostTitle { get; set; }
        public DateTime PostTime { get; set; }//Time of creation"

        //Navigaiton property:
        public virtual Topic? Topic  { get; set; } 
        public virtual List<Comment>? Comments { get; set; }

        public Comment? LatestComment => Comments?.OrderByDescending(c => c.CommentId).FirstOrDefault();
    }
}

MyShop/Models/Room.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models
{
	public class Room
	{
		public int RoomId { get; set; } //PK

        // Apply regular expression validation to RoomName property
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9æøåÆØÅ. \-]{2,20}$", ErrorMessage = "Room Name must be between 2 to 20 characters and can include letters, numbers, or special characters.")]
        public string RoomName { get; set; } = string.Empty; //Gir ingen mening å kunne opprette et forum uten å gi det et navn
        public int CategoryId { get; set; } //FK


        //Navigaiton property:
        public virtual Category? Category { get; set; } // Can't be zero. Virtual enables lazy loading. 
		public virtual List<Topic>? Topics { get; set; } // One room can have many threads, or zero. ? means it can have zero threads.
	}
}

MyShop/Models/Thread.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models
{
	public class Thread
	{
		public int ThreadId { get; set; } //PK
		public int RoomId { get; set; } //FK

		[Required]
		public string ThreadName { get; set; } = string.Empty; //Gir ingen mening å kunne opprette en tråd uten å gi den et navn

        //Navigaiton property:

        public virtual Room room { get; set; } // Can't be zero. Virtual enables lazy loading. 

        public virtual List<Post>? Posts { get; set; } // O
    }
}

MyShop/Controllers/CategoryController.cs
//Getting directives.
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.ViewModels;
using Forum.DAL;

namespace Forum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ILogger<CategoryController> _logger;

        public CategoryController(ICategoryRepository categoryRepository, ILogger<CategoryController> logger)
        {
            _categoryRepository = categoryRepository;
            _logger = logger;
        }

        //Method for the category table page.
        public async Task<IActionResult> CategoryTable()
        {//Getting all categories from the repository.
            var categories = await _categoryRepository.GetAll(); 
            if (categories == null) //If there are no categories found, log an error and returning NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Table");
            return View(categoryListViewModel); //Returning the categoryListViewModel to the view.
        }
        //Method for the categorygrid, pretty much equal to the category table method.
        public async Task<IActionResult> CategoryGrid()
        {
            var categories = await _categoryRepository.GetAll();
            if (categories == null)//If there are no categories found, log an error and return NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Grid");
            return View(categoryListViewModel);
        }
        //Method for the controller for categorydetails, which is a page for one given category
        public async Task<IActionResult> CategoryDetails(int Id) 
        {
            _logger.LogInformation("[CategoryController] Id passed to categorydetails: {Id}.", Id); //Logging the passed Id
            //Using a DAL method to find a category based on it's Id
            var category = await _categoryRepository.GetCategoryById(Id); 
            if (category == null) //Error message if category is null.
            {
                _logger.LogError("[CategoryController] Category not found for the categoryId {Id}.", Id);
                return NotFound("Category not found for the CategoryId");
            }
            return View(category); //Returning to category/categorydetails with the created category.
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory get method
        public IActionResult CreateCategory()
        {
            return View(); //Returns the Category view view
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory post method
        public async Task<IActionResult> CreateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the modelstate is valid (based on requirements found under the model folder
            {
                await _categoryRepository.Create(category); //Passing the category to DAL to create it
                return RedirectToAction(nameof(CategoryTable)); //Redirect to XXX/fotball (Or whatever other category was created).
            }
            _logger.LogWarning("[CategoryController] Category creation failed {@category}", category);
            return View(category); //returning the createCategory view with the category
        }
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can access this method
        public async Task<IActionResult> UpdateCategory(int id) //Method to update a category
        {
            var category = await _categoryRepository.GetCategoryById(id); //getting a category based on id
            if (category == null)
            {
                _logger.LogError("[CategoryController] Category not found when updating the CategoryId {id}", id);
                return BadRequest("Category not found for the CategoryId");
            }
            return View(category); //Returning the UpdateCategory view with the passed category.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //only superadmin can access this method.
        public async Task<IActionResult> UpdateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the method stat is valid based on the model found under Models.
            {
                bool returnOk = await _categoryRepository.Update(category); //Updating category (method in CategoryRepository).
                if (returnOk) //If a true get's passed the client get's redirected to Category/Categorytable.
                    return RedirectToAction(nameof(CategoryTable));
            }
            //logging error, which happens if a true is not returned from the DAL
            _logger.LogWarning("[CategoryController] Category update failed {@category}", category);
            //Returning the category to the UpdateCategory view.
            return View(category); 
        }



        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteCategory(int Id) //Deleting a category based on Id.
        {
            var category = await _categoryRepository.GetCategoryById(Id); //Getting category based on id.
            if (category == null) //checking if the category is null. Logging that the passed if if the category is null.
            {
                _logger.LogError("[CategoryController] Item not found for the CategoryId {Id}", Id);
                return BadRequest("Category not found for the CategoryId"); //returned to erropage.
            }
            return View(category); //Returning to Deletecategory with the category we want to delete passed.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteConfirmedCategory(int Id) //Post method to delete a passed category.
        {
            bool returnOk = await _categoryRepository.Delete(Id); //Passing the category to the DAL to be deleted.
            if (!returnOk) //If the return is not okay, we log the error and return a bad request.
            {

                _logger.LogError("[CategoryController] Category deletion failed for the CategoryId {Id}", Id);
                return BadRequest("Category deletion failed");
            }
            return RedirectToAction(nameof(CategoryTable)); //Redirecting to Category/Categorytable.
        }
    }
}

MyShop/Controllers/CommentController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.ViewModels;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Forum.DAL;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using Microsoft.AspNetCore.Authorization;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.AspNetCore.Identity;

namespace Forum.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _commentRepository;
        private readonly ILogger<CommentController> _logger;
        private readonly UserManager<IdentityUser> _userManager;

        public CommentController(ICommentRepository commentRepository, ILogger<CommentController> logger, UserManager<IdentityUser> userManager)
        {
            _commentRepository = commentRepository;
            _logger = logger;
            _userManager = userManager;
        }

        [HttpGet] //HttpGet is responsible for displaying the form.
        [Authorize] //Any user can access this method.
        public IActionResult CreateComment(int postId) //CreateCommentView with the spesific postId.

        {
            try
            { 
            var comment = new Comment //Creating a new comment.
            {
               PostId = postId //setting the postID of the new comment.
            };
            return View(comment); //Returning the view with the created comment.
            }
            catch (Exception e)
            {
                _logger.LogError(e, "An error occured while creating a comment");
                throw;
            }
        }
        [HttpPost] //HttpPost is responsible for submitting the form.
        [Authorize] //Any user can access this method.
        public async Task<IActionResult> CreateComment(Comment comment)
        {
            try
            { 
            if (ModelState.IsValid)
            {
                    comment.CommentTime = DateTime.Now; //Setting the comment-time.
                    var UserName = _userManager.GetUserName(User); //Getting the username of the current inlogged user from
                    //UserManager.
                    comment.UserName = UserName; //Setting the comments username.
                    await _commentRepository.Create(comment); //Sending the model to the DAL to create a comment
                return RedirectToAction("PostDetails", "Post", new { id = comment.PostId }); //Return to Post/PostDetails/PostId after create.
            }
            _logger.LogWarning("[CommentController] Comment creation failed, ModelState is invalid."); //This gets printed if comment is not valid.
            return View(comment); //returning to Create comment with the created comment passed
            }
            catch (Exception e) //On any other errors we get sent to this loop
            {
                _logger.LogError(e, "An error occurred while creating a comment");
                throw;
            }
        }
        // GET: Comment/
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can update comments
        public async Task<IActionResult> UpdateComment(int Id)
        {
            var Comment = await _commentRepository.GetCommentById(Id); //Getting the current comment based on the passed id

            if (Comment == null) //Looging error the comment is null.
            {
                _logger.LogError("[CommentController]Unable to find comment with ID {Id}", Id);
                return NotFound();
            }

            return View(Comment); //Returning to UpdateComment with the passed comment.
        }

        // POST: Comment
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can access this method.
        public async Task<IActionResult> UpdateComment(Comment comment)
        {
            if (ModelState.IsValid) //Checking if the comment modelstate is valud.
            {
                try
                {
                    await _commentRepository.Update(comment);
                    // Logging for a successful update
                    _logger.LogInformation("Comment updated: {comment}", comment);
                }
                catch(Exception e)
                {
                    //Logging for an error during update
                  _logger.LogError(e, "Error updating comment: {CommentId}", comment);
                }

                return RedirectToAction("PostDetails", "Post", new { id = comment.PostId }); //Return to Post/PostDetails/PostId after create.
            }
            // Logging for an invalid model state
            _logger.LogWarning("Invalid model state when attempting to update comment: {Comment}", comment);

            return View(comment);
        }

        // GET
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //only superadmin can delete comments
        public async Task<IActionResult> DeleteComment(int Id)
        {
            var Comment = await _commentRepository.GetCommentById(Id); //Getting the comment pased on the passed id.

            if (Comment == null)
            {
                //Logging if the comment we got is null
                _logger.LogWarning("Comment not found when attempting to delete. Comment ID: {CommentId}", Id);
                return NotFound();
            }
            // Log that the view for deleting the comment is being displayed
            _logger.LogInformation("Displaying delete view for Comment ID: {Id}", Id);
            return View(Comment);
        }

        // POST
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can use this method
        public async Task<IActionResult> DeleteConfirmedComment(int Id)
        {
            var PostId = await _commentRepository.GetPostId(Id); //Getting postId based on the current commentId
            try
            {
                await _commentRepository.Delete(Id);
                // Log a message that indicate successful deletion of the comment
                _logger.LogInformation("Comment with ID {CommentId} deleted successfully.", Id);

                return RedirectToAction("PostDetails", "Post", new { id = PostId }); //Return to Post/PostDetails/PostId.
            }
            catch(Exception e) 
            {
         
                //Log an error message for deleting not working
                _logger.LogError(e, "Error deleting comment with ID {id]", Id);

                //Redirect to post/Postdetails/PostId on failed delete.
                return RedirectToAction("PostDetails", "Post", new { id = PostId }); 
            }

        }
    }
}

MyShop/Views/Shared/_CategoryCard.cshtml
@model Category


<div class="grid">
    <div>
        <div class="d-flex justify-content-between mt-2">
            <div class="category-item">
                <!-- Display an image specific to the category based on CategoryId -->
                <img src="/images/category_@(Model.CategoryId).jpg" alt="@Model.CategoryName Image" style="max-width: 100%; max-height: 100%    />

                <h5 class="text-start">
                    <!-- Create a link to category details using ASP.NET Core Tag Helpers -->
                    <a asp-controller="Category"
                       asp-action="CategoryDetails"
                       asp-route-id="@Model.CategoryId">@Model.CategoryName</a>
                </h5>
            </div>
        </div>
    </div>
</div>

MyShop/Views/Shared/_CategoryTable.cshtml
@model IEnumerable<Category>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    var categoryIcons = new Dictionary<string, string>
    {

        { "Sport", "fa-futbol-o" },
        { "Data", "fa-desktop" },
        { "Politics", "fa-globe" },
        { "Health", "fa-heart" },
        { "Job", "fa-briefcase" },
        { "Culture,film and music", "fa-film" },
        { "Mobile, tablets and smartwatches", "fa-mobile" },
        { "Economics and law", "fa-money" }
    };
}


<div class="container">
    <div class="category">
        @if (User.IsInRole("SuperAdmin"))
        {
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Category Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model)
                    {
                        <tr>
                            <td><i class="fa fa-fw fa-@category.CategoryName"></i></td>
                            <td><a asp-controller="Category" asp-action="CategoryDetails" asp-route-Id="@category.CategoryId">@category.CategoryName</a></td>
                            <td>
                                <div class="admin-buttons">
                                    <a asp-action="UpdateCategory" asp-route-Id="@category.CategoryId" class="btn btn-success">Update</a>
                                    <a asp-action="DeleteCategory" asp-route-Id="@category.CategoryId" class="btn-admin btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <ul class="list-group">
                @foreach (var category in Model)
                {
                    <li class="list-group-item">
                        <i class="fa fa-fw @categoryIcons[category.CategoryName]"></i>
                        <a asp-controller="Category" asp-action="CategoryDetails" asp-route-Id="@category.CategoryId">@category.CategoryName</a>
                    </li>
                }
            </ul>
        }
        @if (User.IsInRole("SuperAdmin"))
        {
            <div class="create">
                <a class="btn btn-secondary" asp-controller="Category" asp-action="CreateCategory">Create New Category</a>
            </div>
        }
    </div>
</div>

MyShop/Views/Shared/_CommentTable.cshtml
@model IEnumerable<Comment>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<link rel="stylesheet" href="~/css/style.css" />


<head>
    <style>
        .comment-box {
            border: 1px solid #e0e0e0;
            padding: 10px;
            margin-bottom: 10px;
            background-color: #f9f9f9;
        }

            .comment-box table {
                width: 100%;
            }

            .comment-box th {
                font-weight: bold;
                background-color: #333;
                color: white;
            }

            .comment-box td {
                padding: 5px;
            }

            .comment-box .btn {
                margin-right: 5px;
            }

        .comment-text {
            margin-top: 10px;
        }

        .comment-info {
            font-size: 12px;
        }

    </style>
</head>
<div class="container">
    @foreach (var Comment in Model)
    {
        <div class="comment-box">
            <!-- Add a wrapper div for each comment -->
            <table class='table table-striped'>
                <tr>
                    <td>
                        <span>@Comment.CommentDescription</span> <!-- Display the comment description -->
                    </td>
                </tr>
                <tr>
                    <td>
                        <small class="text-muted">Posted @FormatTime(Comment.CommentTime) by @Comment.UserName.</small> <!-- Display the comment's posting time and author -->
                    </td>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <td>
                            <a asp-action="UpdateComment" asp-controller="Comment" asp-route-id="@Comment.CommentId" class="btn btn-success">Update</a> <!-- Button to update the comment for SuperAdmin -->
                            <a asp-action="DeleteComment" asp-controller="Comment" asp-route-id="@Comment.CommentId" class="btn btn-danger">Delete</a> <!-- Button to delete the comment for SuperAdmin -->
                        </td>
                    }
                </tr>
            </table>
        </div>
    }
</div>


@functions {
    string FormatTime(DateTime postTime)
    {
        var timeDifference = DateTime.Now - postTime;

        if (timeDifference.TotalDays >= 1)
        {
            return postTime.ToString("dd MMMM yyyy"); <!-- Format the posting time as date -->
        }
        else if (timeDifference.TotalHours >= 1)
        {
            int hours = (int)timeDifference.TotalHours;
            return $"{hours} {(hours == 1 ? "hour" : "hours")} ago";
            <!-- Format the posting time in hours ago -->
        }
        else if (timeDifference.TotalMinutes >= 1)
        {
            int minutes = (int)timeDifference.TotalMinutes;
            return $"{minutes} {(minutes == 1 ? "minute" : "minutes")} ago"; <!-- Format the posting time in minutes ago -->
        }
        else
        {
            int seconds = (int)timeDifference.TotalSeconds;
            return $"{seconds} {(seconds == 1 ? "second" : "seconds")} ago";
            <!-- Format the posting time in seconds ago -->
        }
    }

}

MyShop/Views/Shared/_Footer.cshtml
<!-- Icon Font Stylesheet -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


<footer class="footer" style="background-color: cadetblue; color: black;">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <!-- Display the website title -->

                 <p class="logo">
                        My Forum 
                     
                  </p>
                <!-- Social media links with icons -->

                <div class="d-flex pt-2   ">
                    <a class="btn btn-outline-light btn-social me-2" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social me-2" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
                <!-- Copyright information for the website -->

                <p class="copyright">
                    Copyright &copy; 2024 by MyForum Inc. All rights reserved.
                </p>
            </div>
            <div class="col-lg-6">
                <div class="footer-heading">
                    <p class="contact-title"> Contact us</p>
                    
                    </div>

                <!-- Contact information for the website -->

                <address class="contacts">
                    
                    <p class="footer-link" href="tel:47-69-48-41">47 69 48 41</p>

                      <a class="footer-link" href="mailto:forum@gmail.com">forum@gmail.com</a>
              
                    
                </address>
            </div>
        </div>
    </div>
</footer>

MyShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>
    <!-- Bootstrap CSS from a CDN -->


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <!-- Stylesheet -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />




</head>
<body>
    <header>
        <!-- Include the "_Navbar" partial view -->
        <partial name="_Navbar" />

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Render the main content body -->
            @RenderBody()
        </main>
    </div>
    <!-- Include the "_Footer" partial view for the website footer -->
    <partial name="_Footer" />

</body>
</html>

MyShop/Views/Shared/_Navbar.cshtml
<header class="bg-white">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center py-0">
            <a class="navbar-brand header-text" asp-area="" asp-controller="Home" asp-action="Index">My Forum</a>
            <div class="ml-5">
                <!-- Partial view for login and user actions -->

                <partial name="_LoginPartial" />
            </div>
        </div>
    </div>
</header>

<!-- Navigation bar -->

<nav class="navbar navbar-expand-md navbar-dark bg-secondary py-0">
    <div class="container">
        <ul class="navbar-nav mr-auto">
            <!-- Navigation links to various sections of the website -->

            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CategoryTable">Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="RoomTable">Room</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="TopicTable">Topic</a>
            </li>
        </ul>


        <form class="d-flex" method="get" action="/Search/Search">
            <!-- Input field for user search -->

            <input class="form-control me-2" placeholder="Search" aria-label="Search" name="search" />
            <!-- Search button with search icon -->

            <button class="btn btn-white border" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

MyShop/Views/Shared/_RoomTable.cshtml
@model IEnumerable<Room>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<div class="container">
    <div class="category">
        <!-- Check if the user is in the "SuperAdmin" role -->
        @if (User.IsInRole("SuperAdmin"))
        {
            <!-- Display a table for room -->

            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Room Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var room in Model)
                    {
                        <tr>
                            <td></td>
                            <!-- Create a link to room details using the RoomId -->

                            <td><a asp-controller="Room" asp-action="RoomDetails" asp-route-id="@room.RoomId">@room.RoomName</a></td>
                            <td>
                                <!-- Display buttons for admin actions -->

                                <div class="admin-buttons">
                                    <!-- Button to update room details -->
                                    <a asp-action="UpdateRoom" asp-controller="Room" asp-route-id="@room.RoomId" class="btn btn-success">Update</a>
                                    <!-- Button to delete a room -->
                                    <a asp-action="DeleteRoom" asp-controller="Room" asp-route-id="@room.RoomId" class="btn-admin btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        //   If the user is not a SuperAdmin, display a simple list of rooms -->
        else
        {
        <ul class="list-group">
            @foreach (var room in Model)
            {
                <li class="list-group-roomitem">
                    <a asp-controller="Room" asp-action="RoomDetails" asp-route-id="@room.RoomId">@room.RoomName</a>

                </li>
            }
        </ul>
        }
    </div>
</div>

MyShop/Views/Shared/_Roomcard.cshtml
@model Room

<div class="col">
    <div>
        <div>
            <div class="d-flex justify-content-between mt-2">
                <!-- Display the RoomName as a link to item details -->

                <h5 class="text-start">
                    <a asp-controller="Item"
                       asp-action="Details"
                       asp-route-id="@Model.RoomId">@Model.RoomName</a>
                </h5>
            </div>
        </div>
    </div>
</div>