MyShop/Controllers/CategoryController.cs
//Getting directives.
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.ViewModels;
using Forum.DAL;

namespace Forum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ILogger<CategoryController> _logger;

        public CategoryController(ICategoryRepository categoryRepository, ILogger<CategoryController> logger)
        {
            _categoryRepository = categoryRepository;
            _logger = logger;
        }

        //Method for the category table page.
        public async Task<IActionResult> CategoryTable()
        {//Getting all categories from the repository.
            var categories = await _categoryRepository.GetAll(); 
            if (categories == null) //If there are no categories found, log an error and returning NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Table");
            return View(categoryListViewModel); //Returning the categoryListViewModel to the view.
        }
        //Method for the categorygrid, pretty much equal to the category table method.
        public async Task<IActionResult> CategoryGrid()
        {
            var categories = await _categoryRepository.GetAll();
            if (categories == null)//If there are no categories found, log an error and return NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Grid");
            return View(categoryListViewModel);
        }
        //Method for the controller for categorydetails, which is a page for one given category
        public async Task<IActionResult> CategoryDetails(int Id) 
        {
            _logger.LogInformation("[CategoryController] Id passed to categorydetails: {Id}.", Id); //Logging the passed Id
            //Using a DAL method to find a category based on it's Id
            var category = await _categoryRepository.GetCategoryById(Id); 
            if (category == null) //Error message if category is null.
            {
                _logger.LogError("[CategoryController] Category not found for the categoryId {Id}.", Id);
                return NotFound("Category not found for the CategoryId");
            }
            return View(category); //Returning to category/categorydetails with the created category.
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory get method
        public IActionResult CreateCategory()
        {
            return View(); //Returns the Category view view
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory post method
        public async Task<IActionResult> CreateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the modelstate is valid (based on requirements found under the model folder
            {
                await _categoryRepository.Create(category); //Passing the category to DAL to create it
                return RedirectToAction(nameof(CategoryTable)); //Redirect to XXX/fotball (Or whatever other category was created).
            }
            _logger.LogWarning("[CategoryController] Category creation failed {@category}", category);
            return View(category); //returning the createCategory view with the category
        }
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can access this method
        public async Task<IActionResult> UpdateCategory(int id) //Method to update a category
        {
            var category = await _categoryRepository.GetCategoryById(id); //getting a category based on id
            if (category == null)
            {
                _logger.LogError("[CategoryController] Category not found when updating the CategoryId {id}", id);
                return BadRequest("Category not found for the CategoryId");
            }
            return View(category); //Returning the UpdateCategory view with the passed category.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //only superadmin can access this method.
        public async Task<IActionResult> UpdateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the method stat is valid based on the model found under Models.
            {
                bool returnOk = await _categoryRepository.Update(category); //Updating category (method in CategoryRepository).
                if (returnOk) //If a true get's passed the client get's redirected to Category/Categorytable.
                    return RedirectToAction(nameof(CategoryTable));
            }
            //logging error, which happens if a true is not returned from the DAL
            _logger.LogWarning("[CategoryController] Category update failed {@category}", category);
            //Returning the category to the UpdateCategory view.
            return View(category); 
        }



        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteCategory(int Id) //Deleting a category based on Id.
        {
            var category = await _categoryRepository.GetCategoryById(Id); //Getting category based on id.
            if (category == null) //checking if the category is null. Logging that the passed if if the category is null.
            {
                _logger.LogError("[CategoryController] Item not found for the CategoryId {Id}", Id);
                return BadRequest("Category not found for the CategoryId"); //returned to erropage.
            }
            return View(category); //Returning to Deletecategory with the category we want to delete passed.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteConfirmedCategory(int Id) //Post method to delete a passed category.
        {
            bool returnOk = await _categoryRepository.Delete(Id); //Passing the category to the DAL to be deleted.
            if (!returnOk) //If the return is not okay, we log the error and return a bad request.
            {

                _logger.LogError("[CategoryController] Category deletion failed for the CategoryId {Id}", Id);
                return BadRequest("Category deletion failed");
            }
            return RedirectToAction(nameof(CategoryTable)); //Redirecting to Category/Categorytable.
        }
    }
}

MyShop/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;

using Forum.DAL;
using Forum.Models;
using Forum.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Text.Json;


namespace Forum.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICommentRepository _commentRepository;
        private readonly ILogger<PostController> _logger;
        private readonly UserManager<IdentityUser> _userManager;



        public PostController(IPostRepository postRepository, ICommentRepository commentRepository, ILogger<PostController> logger, UserManager<IdentityUser> userManager)
        {
            _postRepository = postRepository;
            _commentRepository = commentRepository; 
            _logger = logger;
            _userManager = userManager;
        }

        [HttpGet] //Called when clicking on the CreatePost hypelink under TopicDetails. CreatePost is the name of the method (here) and view (CreatePost.cshtml).
        [Authorize]
        public IActionResult CreatePost(int TopicId) //Create a post with a given Id, which is (should be) passed  when the method is called.
        {
            try
            {
                var postCommentViewModel = new PostCommentViewModel
                {
                    Post = new Post { TopicId = TopicId }, //Setting the ViewModels post and comment, and the Post inside the viewmodels TopicId.
                    Comment = new Comment()
                };
                return View(postCommentViewModel); // Returns the view with the initialized post and comment.
            }
            catch (Exception e)
            {
                _logger.LogError(e, "An error occurred while creating a post");
                throw;
            }
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreatePost(PostCommentViewModel postCommentViewModel)
        {
            var time = DateTime.Now; //Creating a variable "time" To be used as time for both the first posted
            postCommentViewModel.Post.PostTime = time;
            postCommentViewModel.Comment.CommentTime = time; //Setting commentime
            if (ModelState.IsValid)
            {
                var UserName = _userManager.GetUserName(User);
                postCommentViewModel.Post.UserName = UserName;
                await _postRepository.Create(postCommentViewModel.Post); //Creating post
                postCommentViewModel.Comment.PostId = postCommentViewModel.Post.PostId; //Then assigning the Comments postId equal to Posts Postid
                postCommentViewModel.Comment.UserName = UserName; //Then assigning the Comments postId equal to Posts Postid
                var serializedModel = JsonSerializer.Serialize(postCommentViewModel, new JsonSerializerOptions
                {
                    WriteIndented = true,
                    ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.Preserve
                });
                _logger.LogInformation("Attempting to create a new post and comment with the following data: {PostCommentViewModel}", serializedModel);
                await _commentRepository.Create(postCommentViewModel.Comment); //Then I can create the comment.
                return RedirectToAction("TopicDetails", "Topic", new { id = postCommentViewModel.Post.TopicId });//Return to Topic/TopicDetails/TopicId after create.
            }

            _logger.LogWarning("[PostController] Post creation failed {@post}", postCommentViewModel.Post);
            return View(postCommentViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> PostDetails(int Id)
        {
            var post = await _postRepository.GetPostById(Id);

            if (post == null)
            {
                _logger.LogError("[PostController] post not found for the TopicId {PostId:0000}", Id);
                return NotFound("Post not found!");
            }
            // Send rommet til visningen for topicetaljer
            return View(post);
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> UpdatePost(int Id)
        {
            var Post = await _postRepository.GetPostById(Id);

            if (Post == null)
            {
                _logger.LogError("The post with ID {PostId} was not found.", Id);
                return NotFound();
            }

            return View(Post);
        }

        // POST: Topic
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> UpdatePost(Post post)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await _postRepository.Update(post);
                }
                catch(Exception e)
                {
                    _logger.LogError("An error occurred while updating the post", e);
                }

                return RedirectToAction("TopicDetails", "Topic", new { id = post.TopicId }); ;
            }
            _logger.LogError("Model validation failed for Post");

            foreach (var state in ModelState)
            {
                foreach (var error in state.Value.Errors)
                {
                    _logger.LogError($"Key: {state.Key}, Error: {error.ErrorMessage}");
                }
            }

            return View(post);
        }

        // GET
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeletePost(int Id)
        {
            var topic = await _postRepository.GetPostById(Id);

            if (topic == null)
            {
                _logger.LogError("[PostController] post not found for the PostId {PostId:0000}", Id);
                return BadRequest("Category not found for the CategoryId");
            }
            return View(topic);
        }

        // POST
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmedPost(int Id)
        {
            var TopicId = await _postRepository.GetTopicId(Id);
            bool returnOk = await _postRepository.Delete(Id);
            if (!returnOk)
            {
                _logger.LogError("[TopicController] Topic deletion failed for the TopicId {TopicId:0000}", Id);
                return BadRequest("topic deletion failed");

            }

            return RedirectToAction("TopicDetails", "Topic", new { id = TopicId });

        }
    }


}

MyShop/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;

namespace Forum.Controllers
{
    public class SearchController : Controller
    {
        private readonly CategoryDbContext _db;
        private readonly ILogger<SearchController> _logger; 

        public SearchController(CategoryDbContext db, ILogger<SearchController> logger) 
        {
            _db = db;
            _logger = logger;
        }

        // A Search method for handling search requests.
        // It takes a search parameter, which is provided by the user's input in the search query.
        [HttpGet]
            public IActionResult Search(string search)
            {
                try
                {
                    if (string.IsNullOrWhiteSpace(search))
                    {
                   // If the query is empty, return an empty list
                    return View(new SearchResultViewModel());
                    }

                //his code gets a list of categories/post/comments from the database,
                //filters them based on a case-insensitive search for search within their names, and stores the filtered list in the categories/post/comment variable.
                var categories = _db.Categories.ToList()
                     .Where(category => category.CategoryName.Contains(search, StringComparison.OrdinalIgnoreCase))
                     .ToList();
                

                var posts = _db.Posts.ToList()
                   .Where(post => post.PostTitle.Contains(search, StringComparison.OrdinalIgnoreCase))
                   .ToList();


    
                  var commment = _db.Comments.ToList()
                         .Where(commment => commment.CommentDescription.Contains(search, StringComparison.OrdinalIgnoreCase))
                             .ToList();

                    var searchResults = new SearchResultViewModel
                    {
                        Categories = categories,
                        Posts = posts,
                  
                        Comments = commment
                    };
                //Returns the list 
                    return View(searchResults);
                }
            //exception during the search operation, it logs errod and return error View 
            catch (Exception e)
                {
                    _logger.LogError(e, "An error occurred during the search.");
                    return View("Error");
                }
            }
        }
    }

MyShop/Views/Search/Search.cshtml
@model SearchResultViewModel

<style>
    .result-post {
        border: 1px solid #fff;
        border-radius: 10px;
        margin: 10px 0;
        padding: 10px;
        background-color: #f9f9f9;
        color: #333;
    }

    .result-count {
        padding: 0.4rem 1rem;
        border-radius: 3px;
        color: #fff;
        background-color: #7393B3;
        margin-top:20px;
    }
</style>
<h1>Search Results</h1>

@{
    int totalResults = (Model.Categories?.Count ?? 0)  + (Model.Posts?.Count ?? 0) + (Model.Comments?.Count ?? 0);
}

<div class="result-container">
    <div class="search-results">
        @if (totalResults == 0)
        {

            <form class="d-flex" method="get" action="/Search/Search">
                <input class="form-control me-2" placeholder="Search" aria-label="Search" name="search" />
                <button class="btn btn-white border" type="submit"><i class="fas fa-search"></i></button>
            </form>
            <div class="no-results">
                <div class="result-count">
                    <p>Found @totalResults results</p>
                </div>
                <p>We couldn't find any matches for your search. You can try a more general search or modify some of the criteria.</p>
            </div>
        }
        else
        {

            <form class="d-flex" method="get" action="/Search/Search">
                <input class="form-control me-2" placeholder="Search" aria-label="Search" name="search" />
                <button class="btn btn-white border" type="submit"><i class="fas fa-search"></i></button>
            </form>
            <div class="result-count">

                <p>Found @totalResults results</p>
            </div>

            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                @foreach (var category in Model.Categories)
                {
                    <div class="result-post">
                        <a href="@Url.Action("CategoryDetails", "Category", new { id = category.CategoryId })">@category.CategoryName</a>
                    </div>
                }
            }

            @if (Model.Posts != null && Model.Posts.Count > 0)
            {
                @foreach (var post in Model.Posts)
                {
                    <div class="result-post">
                        <a href="@Url.Action("PostDetails", "Post", new { id = post.PostId })">@post.PostTitle</a>

                        @{
                            // Get the post creation time from the model
                            var postTime= post.PostTime;

                          
                            // Call the FormatTimeAgo helper function to format the time
                            var time = FormatTime(postTime);

                        }

                        <p>@time</p>
                    

                    </div>
                }
            }

            @if (Model.Comments != null && Model.Comments.Count > 0)
            {
                @foreach (var comment in Model.Comments)
                {
                    <div class="result-post">
                        <a href="@Url.Action("PostDetails", "Post", new { id = comment.PostId })">@comment.CommentDescription</a>

                        @{
                            // Get the post creation time from the model
                            var commentTime = comment.CommentTime;


                            // Call the FormatTimeAgo helper function to format the time
                            var time = FormatTime(commentTime);

                        }

                        <p>@time</p>


                    </div>
                }
            }
          



        }
    </div>
</div>


@functions {
        string FormatTime(DateTime postTime)
        {
            var timeDifference = DateTime.Now - postTime;

            if (timeDifference.Days >= 1)
            {
                if ((int)timeDifference.Days == 1)
                {
                    return $"{(int)timeDifference.Days} day ago";
                }
                else
                {
                    return $"{(int)timeDifference.Days} days ago";
                }
            }
            else if (timeDifference.Hours >= 1)
            {
                if ((int)timeDifference.Hours == 1)
                {
                    return $"{(int)timeDifference.Hours} hour ago";
                }
                else
                {
                    return $"{(int)timeDifference.Hours} hours ago";
                }
            }
            else if (timeDifference.Minutes >= 1)
            {
                if ((int)timeDifference.Minutes == 1)
                {
                    return $"{(int)timeDifference.Minutes} minute ago";
                }
                else
                {
                    return $"{(int)timeDifference.Minutes} minutes ago";
                }
            }
            else
            {
                if ((int)timeDifference.TotalSeconds == 1)
                {
                    return $"{(int)timeDifference.Seconds} second ago";
                }
                else
                {
                    return $"{(int)timeDifference.Seconds} seconds ago";
                }
            }
        }
}