MyShop/Models/Room.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models
{
	public class Room
	{
		public int RoomId { get; set; } //PK

        // Apply regular expression validation to RoomName property
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9æøåÆØÅ. \-]{2,20}$", ErrorMessage = "Room Name must be between 2 to 20 characters and can include letters, numbers, or special characters.")]
        public string RoomName { get; set; } = string.Empty; //Gir ingen mening å kunne opprette et forum uten å gi det et navn
        public int CategoryId { get; set; } //FK


        //Navigaiton property:
        public virtual Category? Category { get; set; } // Can't be zero. Virtual enables lazy loading. 
		public virtual List<Topic>? Topics { get; set; } // One room can have many threads, or zero. ? means it can have zero threads.
	}
}

MyShop/Controllers/CategoryController.cs
//Getting directives.
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.ViewModels;
using Forum.DAL;

namespace Forum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ILogger<CategoryController> _logger;

        public CategoryController(ICategoryRepository categoryRepository, ILogger<CategoryController> logger)
        {
            _categoryRepository = categoryRepository;
            _logger = logger;
        }

        //Method for the category table page.
        public async Task<IActionResult> CategoryTable()
        {//Getting all categories from the repository.
            var categories = await _categoryRepository.GetAll(); 
            if (categories == null) //If there are no categories found, log an error and returning NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Table");
            return View(categoryListViewModel); //Returning the categoryListViewModel to the view.
        }
        //Method for the categorygrid, pretty much equal to the category table method.
        public async Task<IActionResult> CategoryGrid()
        {
            var categories = await _categoryRepository.GetAll();
            if (categories == null)//If there are no categories found, log an error and return NotFound.
            {
                _logger.LogError("[CategoryController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            //Creating a listviewmodel with the categories .
            var categoryListViewModel = new CategoryListViewModel(categories, "Grid");
            return View(categoryListViewModel);
        }
        //Method for the controller for categorydetails, which is a page for one given category
        public async Task<IActionResult> CategoryDetails(int Id) 
        {
            _logger.LogInformation("[CategoryController] Id passed to categorydetails: {Id}.", Id); //Logging the passed Id
            //Using a DAL method to find a category based on it's Id
            var category = await _categoryRepository.GetCategoryById(Id); 
            if (category == null) //Error message if category is null.
            {
                _logger.LogError("[CategoryController] Category not found for the categoryId {Id}.", Id);
                return NotFound("Category not found for the CategoryId");
            }
            return View(category); //Returning to category/categorydetails with the created category.
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory get method
        public IActionResult CreateCategory()
        {
            return View(); //Returns the Category view view
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only a superadmin can access the createcategory post method
        public async Task<IActionResult> CreateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the modelstate is valid (based on requirements found under the model folder
            {
                await _categoryRepository.Create(category); //Passing the category to DAL to create it
                return RedirectToAction(nameof(CategoryTable)); //Redirect to XXX/fotball (Or whatever other category was created).
            }
            _logger.LogWarning("[CategoryController] Category creation failed {@category}", category);
            return View(category); //returning the createCategory view with the category
        }
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can access this method
        public async Task<IActionResult> UpdateCategory(int id) //Method to update a category
        {
            var category = await _categoryRepository.GetCategoryById(id); //getting a category based on id
            if (category == null)
            {
                _logger.LogError("[CategoryController] Category not found when updating the CategoryId {id}", id);
                return BadRequest("Category not found for the CategoryId");
            }
            return View(category); //Returning the UpdateCategory view with the passed category.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //only superadmin can access this method.
        public async Task<IActionResult> UpdateCategory(Category category)
        {
            if (ModelState.IsValid) //Checking if the method stat is valid based on the model found under Models.
            {
                bool returnOk = await _categoryRepository.Update(category); //Updating category (method in CategoryRepository).
                if (returnOk) //If a true get's passed the client get's redirected to Category/Categorytable.
                    return RedirectToAction(nameof(CategoryTable));
            }
            //logging error, which happens if a true is not returned from the DAL
            _logger.LogWarning("[CategoryController] Category update failed {@category}", category);
            //Returning the category to the UpdateCategory view.
            return View(category); 
        }



        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteCategory(int Id) //Deleting a category based on Id.
        {
            var category = await _categoryRepository.GetCategoryById(Id); //Getting category based on id.
            if (category == null) //checking if the category is null. Logging that the passed if if the category is null.
            {
                _logger.LogError("[CategoryController] Item not found for the CategoryId {Id}", Id);
                return BadRequest("Category not found for the CategoryId"); //returned to erropage.
            }
            return View(category); //Returning to Deletecategory with the category we want to delete passed.
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> DeleteConfirmedCategory(int Id) //Post method to delete a passed category.
        {
            bool returnOk = await _categoryRepository.Delete(Id); //Passing the category to the DAL to be deleted.
            if (!returnOk) //If the return is not okay, we log the error and return a bad request.
            {

                _logger.LogError("[CategoryController] Category deletion failed for the CategoryId {Id}", Id);
                return BadRequest("Category deletion failed");
            }
            return RedirectToAction(nameof(CategoryTable)); //Redirecting to Category/Categorytable.
        }
    }
}

MyShop/Controllers/TopicController.cs
using Forum.DAL;
using Forum.Models;
using Forum.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Forum.Controllers
{
    public class TopicController : Controller
    {
        private readonly ITopicRepository _topicRepository;
        private readonly ILogger<TopicController> _logger;


        public TopicController(ITopicRepository topicRepository, ILogger<TopicController> logger)
        {
            _topicRepository = topicRepository;
            _logger = logger;
        }

        //Method for theTopicTable-sida
        public async Task<IActionResult> TopicTable()
        {
            var topics = await _topicRepository.GetAll(); //Getting all topic
            if (topics == null) //If-test and logging if no topics are found
            {
                _logger.LogError("[TopicController] Topic list not found while executing _topicRepository.GetAll()");
            }
            var topicListViewModel = new TopicListViewModel(topics, "Table"); //Creating a new topicListViewModel.
            return View(topicListViewModel); //Returning to topictable with the passed topiclistviewmodel.
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only superadmin can access this method
        //Get method for the createtopic-page with a passed roomId
        public IActionResult CreateTopic(int roomId)
        {
            try
            {
                var topic = new Topic //Creating a new topic and setting the topics RoomId equal to the passed roomId
                {
                    RoomId = roomId
                };
                return View(topic); //Returning the create view with the passed topic.
            }
            catch (Exception ex) //If topic creation failed we log an error and return a 404 not found
            {
                _logger.LogError(ex, "An error occurred while creating a topic");
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Accessible only to SuperAdmin
        public async Task<IActionResult> CreateTopic(Topic topic)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Save Topic entity
                    await _topicRepository.Create(topic);
                    //Redirecting to RoomDetails/Room/*Newly created topics Id* on successfull create.
                    return RedirectToAction("RoomDetails", "Room", new { id = topic.RoomId });
                } //On invalid model state, returning to the CreateTopic view and passing the topic. Logging the topicId on 
                _logger.LogInformation("Created a new topic with id {id}", topic.TopicId);
                return View(topic);
            }
            catch (Exception ex) //For any other errors than invalid model state, we log a generi error message and return a 404 not found.
            {
                _logger.LogError(ex, "[TopicController]An error occurred while creating a topic");
                return NotFound();
            }
        }

        [HttpGet] //Displays the details of a topic with a given Id. 
        public async Task<IActionResult> TopicDetails(int Id)
        {
            var topic = await _topicRepository.GetTopicById(Id); //Getting the topicrepo based on id.

            if (topic== null)
            {
                _logger.LogError("[TopicController] Topic not found for the TopicId {TopicId:0000}", Id);
                return NotFound("Topic not found."); //This page will popup only if we try to access a page where topic is null.
            }

            // Sends the given topic to the view.
            return View(topic);
        }

        // GET: Comment/
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin.
        public async Task<IActionResult> UpdateTopic(int Id)
        {
            var Topic = await _topicRepository.GetTopicById(Id);//Getting the topicrepo based on id.

            if (Topic == null) //Returning not found if Topic is null
            {
                return NotFound();
            }

            return View(Topic); //If a topic is found, returning the updatedtopic view with the passed topic
        }

        // POST: Topic

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin
        public async Task<IActionResult> UpdateTopic(Topic topic)
        {

            if (ModelState.IsValid) //Checking if modelstate is valid
            {
                try
                {
                    await _topicRepository.Update(topic); //Attempting to update topic.
                }
                catch(Exception e) //Reaching the exception if update of topic failed.
                {
                    _logger.LogError("Could not update topic",e);
                }
                return RedirectToAction("RoomDetails", "Room", new { id = topic.RoomId }); //Redirecting to the Room of the newly updated topic.
            }
            else { _logger.LogError("ModeState is not valid for topic"); } //We only reach this log if the modelstate is not valid. After logging we return the updatetopic view with the topic.
            return View(topic);
        }


        // GET
        [HttpGet]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin
        public async Task<IActionResult> DeleteTopic(int id)
        {
            var topic = await _topicRepository.GetTopicById(id); //Getting a topic based on id.

            if (topic == null) //Logging error if topic is null
            {
                _logger.LogError("[TopicController] topic not found for the TopicId {Id}", id);
                return BadRequest("Topic not found for the TopicId");
            }

            return View(topic); //returning deleteopic view with the created topic
        }

        // POST
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")] //Only accessible to superadmin
        public async Task<IActionResult> DeleteConfirmedTopic(int Id)
        {
            var RoomId = await _topicRepository.GetRoomId(Id); //Getting the roomid of the topic we are going to delete
            bool returnOk = await _topicRepository.Delete(Id); //Deleting the topic based on id
            if (!returnOk) //Entering the loop if the DAL did not return a true and logging + returning a bad request. 
            {
                _logger.LogError("[TopicController] Topic deletion failed for the TopicId {Id}", Id);
                return BadRequest("topic deletion failed");
            }
            return RedirectToAction("RoomDetails", "Room", new { id = RoomId }); //Redirecting to Room/Roomdetails/*RoomId of the deleted topic*
        }
    }
}

MyShop/Views/Room/CreateRoom.cshtml
@model Room



<form asp-action="CreateRoom">
    <div class="form-group">
        <label asp-for="RoomName" style="margin-bottom:10px"></label><span class="text-danger">*</span>
        <input asp-for="RoomName" class="form-control" />
        <span asp-validation-for="RoomName" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="CategoryId" value="@Model.CategoryId" />
    <!-- Adds a hidden input for CategoryId, which is sent to the server when the form is submitted -->
    <!-- This is useful for storing CategoryId and associating the room with a specific category. -->

    <button type="submit" class="btn btn-primary" style="margin-top:10px">Create</button>
    <!-- Creates a "Create" button to submit the form to the server -->

    <a asp-controller="Category" asp-action="CategoryDetails" asp-route-id="@Model.CategoryId" class="btn btn-secondary" style="margin-top:10px">Back to Category Details</a>
    <!-- Creates a "Back to Category Details" link that takes you back to the category details -->
</form>

MyShop/Views/Room/DeleteRoom.cshtml
@model Room

<h2>Delete room </h2>

<div>

    <h4>Room</h4>

    <dl class="row">
        <dt class="col-sm-2">Room Id</dt>
        <dd class="col-sm-10">@Model.RoomId </dd>

        <dt class="col-sm-2">Name</dt>
        <dd class="col-sm-10">@Model.RoomName</dd>

    </dl>

    <!-- Starts a form that submits data to the "DeleteConfirmedRoom" action with "RoomId" as a route value upon submission (HTTP POST). -->

    <form asp-action="DeleteConfirmedRoom" asp-route-id="@Model.RoomId" method="post">

        <!--Button to confirmt deletetion of room -->
            <button type="submit" class="btn  btn-danger">Delete</button>
        <!--Return button, which returns the user to the previous page-->
        <a asp-controller="Category" asp-action="CategoryDetails" asp-route-id="@Model.CategoryId" class="btn btn-secondary">Cancel</a>
    </form>
     
  </div>

MyShop/Views/Room/RoomDetails.cshtml
@model Forum.Models.Room
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<a class="navigation-link asp-controller="Home" asp-action="Index">Home ></a>
<a class="navigation-link asp-action="CategoryDetails" asp-controller="Category" asp-route-id="@Model.CategoryId" class="link-primary">@Model.Category.CategoryName ></a>
<a class="navigation-link">@Model.RoomName</a>

<H1>@Model.RoomName</H1>


<partial name="_TopicTable" model="Model.Topics" />

@if (User.IsInRole("SuperAdmin"))
{
    <a class="btn btn-primary" class="create" style="margin-left: 110px;"
   asp-controller="Topic"
   asp-action="CreateTopic"
   asp-route-roomId="@Model.RoomId">Create New Topic</a>
}

MyShop/Views/Room/RoomGrid.cshtml
@model RoomListViewModel

<h1>List of rooms (@Model.CurrentViewName View)</h1>
<a href="/Room/RoomTable">Table View</a>

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var room in Model.Rooms)
    {
        <partial name="_RoomCard" model="room" />
    }
</div>

MyShop/Views/Room/RoomTable.cshtml
@model RoomListViewModel

<div class="heading">
    <h3>Rooms</h3>
</div>

<partial name="_RoomTable" model="Model.Rooms" />

MyShop/Views/Room/UpdateRoom.cshtml
@model Room

<h2>Update Room</h2>

<form asp-action="UpdateRoom">
    <input type="hidden" asp-for="RoomId" />
    <input type="hidden" asp-for="CategoryId" />

    <div>
        <label asp-for="RoomName"></label>
        <input asp-for="RoomName" class="form-control" />
        <span aps-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save changes</button>
    <a asp-controller="Category" asp-action="CategoryDetails" asp-route-id="@Model.CategoryId" class="btn btn-secondary">Cancel</a>


</form>